PRAGMA foreign_keys = ON;

-- Demo site builds generated by Step 1 keyword list + LLM codegen.
CREATE TABLE IF NOT EXISTS demo_site_builds (
  build_id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL,
  site_url TEXT NOT NULL,
  research_run_id TEXT,
  status TEXT NOT NULL DEFAULT 'queued', -- queued|running|success|failed
  keywords_json TEXT NOT NULL,
  source_r2_prefix TEXT,
  output_r2_prefix TEXT,
  error_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
  updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
  FOREIGN KEY (site_id) REFERENCES wp_ai_seo_sites(site_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_demo_site_builds_site_time
  ON demo_site_builds(site_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_demo_site_builds_status_time
  ON demo_site_builds(status, created_at DESC);

